# Generated by Django 4.0.6 on 2022-07-04 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('username', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('conversation_id', models.IntegerField()),
                ('created_at', models.CharField(max_length=70)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('timezone', models.CharField(max_length=70)),
                ('tweet', models.TextField(max_length=500)),
                ('language', models.CharField(max_length=70)),
                ('replies_count', models.IntegerField()),
                ('retweets_count', models.IntegerField()),
                ('likes_count', models.IntegerField()),
                ('link', models.CharField(max_length=70)),
                ('retweet', models.BooleanField()),
                ('auhtor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.author')),
            ],
        ),
    ]
