# Generated by Django 4.0.6 on 2022-07-19 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='auhtor',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='author',
            name='id',
        ),
        migrations.AlterField(
            model_name='author',
            name='user_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
