# Generated by Django 4.0.6 on 2022-07-19 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_auhtor_tweet_user_id_remove_author_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='created_at',
        ),
    ]
